###
### Bolt Forms
###


# reCAPTCHa set up
recaptcha:
  enabled: false
  label: "Please enter the reCaptcha text to prove you're a human"
  public_key: ''
  private_key: ''
  error_message: "The CAPTCHA wasn't entered correctly. Please try again."
  theme: clean

## CSRF protection
#
# Enable CSRF protection for forms. You should leave this set to 'true', unless
# you know what you're doing.
csrf: true

## Debugging
#
# Global debugging on/off switch
#
# If enabled, ALL forms will go into debug mode.  However, when disabled an individual
# form can still enable it's own debug — specific for and to that form
debug:
  enabled: true  
  address: romulo1984@gmail.com

contato:
    notification:
        enabled: true
        debug: false
        subject: Contato pelo site Assédio
        attach_files: false
        to_name: Assédio Coletivo
        to_email: no-reply@assedicoletivo.com.br
        from_name: nome
        from_email: email
    feedback:
        success: Mensagem enviada com Sucesso
        error: Sua mensagem não pode ser enviada. Tente novamente mais tarde.
    database:
        contenttype: contatos
    fields:
        nome:
            type: text
            required: true
            options:
                attr:
                    placeholder: Seu nome...
                    class: form-control input-lg
                constraints: [ NotBlank, {Length: {'min': 3}} ]
        email:
            type: email
            options:
                required: true
                attr:
                    placeholder: Seu e-mail...
                    class: form-control input-lg
                constraints: [ NotBlank, Email ]
        mensagem:
            type: textarea
            options:
                required: true
                attr:
                    placeholder: Sua mensagem...
                    class: form-control input-lg
        submit:
            type: submit
            options:
                attr:
                    class: btn btn-lg btn-default
        

## Example 1
#
# Contact Form
contact:
  notification:
    enabled: true
    debug: false
    subject: Your message was submitted 
    to_name: My Site              # Must be valid text
    to_email: noreply@example.com # Must be valid email address
    from_name: name               # A field name, specified in the fields: section below
    from_email: email             # A field name, specified in the fields: section below
    cc_name: Info Person
    cc_email: info@example.com
    bcc_name: Manager Person
    bcc_email: manager@example.com
    attach_files: false
  feedback:
    success: Message submission sucessful
    error: There are errors in the form, please fix before trying to resubmit 
  database:
    contenttype: contatos  # Contenttype to create
#    table: bolt_secret_table    # Specific database table to write to
  fields:
    nome:
      type: text
      required: true
      options:
        label: Nome
        attr:
          placeholder: Seu nome...
          class: form-control input-lg
        constraints: [ NotBlank, {Length: {'min': 3}} ]
    email:
      type: email
      options:
        required: true
        label: E-mail
        attr:
          placeholder: Seu e-mail...
          class: form-control input-lg
        constraints: [ NotBlank, Email ]
    message:
      type: textarea
      options:
        required: true
        label: Mensagem
        attr:
          placeholder: Sua mensagem...
          class: form-control input-lg
    needreply:
      type: choice
      options:
        required: false
        label: Do you want us to contact you back?
        choices: [ Yes, No ]
        multiple: false
    submit:
      type: submit

## Example 2
#
# Example Showcase Form
Showcase:
  notification:
    enabled: true
    debug: false
    subject: "[TESTING] A showcase form was just submitted" 
    to_name: My Site              # Must be valid text
    to_email: noreply@example.com # Must be valid email address
    from_name: name               # A field name, specified in the fields: section below
    from_email: email             # A field name, specified in the fields: section below
    cc_name: Info Person
    cc_email: info@example.com
    bcc_name: Manager Person
    bcc_email: manager@example.com
    attach_files: false
  feedback:
    success: Form submission sucessful
    error: There are errors in the form, please fix before trying to resubmit
#  database:
#    contenttype: mycontenttype  # Contenttype to create
#    table: bolt_secret_table    # Specific database table to write to
  fields:
    subject:
      type: text
      required: true
      options:
        label: Subject of your message
        attr:
          placeholder: Just a quick message...
        constraints: [ NotBlank, {Length: {'min': 3, 'max': 30}} ]
    name:
      type: text
      required: true
      options:
        label: Name
        attr:
          placeholder: Your name...
        constraints: [ NotBlank, {Length: {'min': 3}} ]
    email:
      type: email
      options:
        required: true
        label: Email address
        attr:
          placeholder: Your email...
          class: myclass-email
        constraints: [ NotBlank, Email ]
    message:
      type: textarea
      options:
        required: true
        label: Your message
        attr:
          placeholder: Well, the other day I was thinking that maybe you ought to improve your website by adding...
          class: myclass-message
    needreply:
      type: choice
      options:
        required: false
        label: Do you want us to contact you back?
        choices: [ Yes, No ]
        multiple: false
