# This is the config file for the Simple Forms extension.

stylesheet: assets/simpleforms.css
template: assets/simpleforms_form.twig
mail_template: assets/simpleforms_mail.twig
message_ok: Obrigado! Sua mensagem foi enviada com sucesso.
message_error: Houve um erro no formulário. Por favor, verifique os dados inseridos e tente novamente
message_technical: Houve algumas dificuldades técnicas e a sua mensagem não foi enviada. Pedimos desculpas pelo inconveniente.
button_text: Enviar
# Optional. Used only, when you have a file field.
# mime_types_message: "Not allowed file type. Allowed file types are:"

# ReCaptcha Config - Set these options to enable ReCaptcha spam protection.
# Generate your keys at https://www.google.com/recaptcha/admin/create
recaptcha_enabled: false
recaptcha_public_key: ''
recaptcha_private_key: ''
recaptcha_error_message: "The CAPTCHA wasn't entered correctly. Please try again."
recaptcha_theme: clean

# Enable CSRF protection for forms. You should leave this set to 'true', unless
# you know what you're doing.
csrf: true

# Default fallback sender email
# this is required because Swiftmailer will reject the message without one
# please make this a sensible existing email address
from_email: romuloguimaraes@oparque.art.br
from_name: Assédio Coletivo

# global cc email address
# set this value to an email address that will receive a copy of every email from simpleforms
# recipient_cc_email: info@example.com
# recipient_cc_name: Info

# global bcc email address
# set this value to an email address that will receive a blind copy of every email from simpleforms
# recipient_bcc_email: info@example.com

# global testmode
# for development all email will be sent to this address
# all other recipient and cc addresses will be ignored
# remove or set 'testmode' to false for a production site
testmode : false
testmode_recipient: romuloguimaraes@oparque.art.br

# from_email and from_name can be set for picky SMTP servers

# A simple contact form. Use as {{ simpleform('contact') }} in your templates.
contato:
    recipient_email: assediocoletivo@gmail.com.br
    recipient_name: Assédio Coletivo
    mail_subject: "[Assédio Coletivo] Contato pelo Site"
    fields:
        nome:
            type: text
            required: true
            placeholder: Seu nome...
        email:
            type: email
            label: E-mail
            required: true
            placeholder: Seu e-mail...
        mensagem:
            type: textarea
            required: true
            placeholder: Sua Mensagem...
    button_text: Enviar