paginas:
    name: Páginas
    singular_name: Página
    fields:
        titulo:
            label: Título
            type: text
            class: large
        slug:
            type: slug
            uses: titulo
        imagem-destaque:
            label: Imabem de Destaque
            type: image
            postfix: "<p><em>Nem todas as páginas contém uma imagem de destaque exibida, mas é importante adicioná-la, para gerar metatags que serão lidas pelo Facebook.</em></p>"
        resumo:
            type: textarea
        corpo:
            type: html
            height: 300px
    searchable: false

noticias:
    name: Notícias
    singular_name: Notícia
    fields:
        titulo:
            label: Título
            type: text
            class: large
        slug:
            type: slug
            uses: titulo
        titulo-destaque:
            label: Título de Destaque
            type: text
            class: large
            postfix: "<p><em>O título destaque aparece apenas em algumas páginas, como nos blocos da home.</em></p>"
        imagem-destaque:
            label: Imagem de Destaque
            type: image
        resumo:
            type: textarea
        corpo:
            type: html
            height: 300px
        data:
            label: Data do evento (para agenda)
            type: date
            postfix: "<p><em>Só preencha esta informação caso a categoria seja <strong>AGENDA</strong></em></p>"
    taxonomy: [ categorias, tags ]
    relations:
        galerias:
            multiple: false
            label: Selecione uma galeria
            postfix: "<p><em>Só escolha uma galeria caso a notícia precise exibir alguma.</em></p>"
    default_status: publish

projetos:
    name: Projetos
    singular_name: Projeto
    fields:
        titulo:
            label: Título
            type: text
            class: large
        slug:
            type: slug
            uses: titulo
        titulo-destaque:
            label: Título de Destaque
            type: text
            class: large
            postfix: "<p><em>O título destaque aparece apenas em algumas páginas, como nos blocos da home.</em></p>"
        imagem-destaque:
            label: Imagem de Destaque
            type: image
            postfix: "<p><em>Esta é a imagem que aparece no fundo do filete (é recomendável uma imagem com pelo menos 900px de altura)</em></p>"
        logo:
            type: image
            postfix: "<p><em>Este é o logo que aparece no filete do projeto, na galeria de projetos.</p>"
        cor-titulo:
            type: colourpicker
            label: Cor do Título
            postfix: "<p><em>Escolha uma cor que gere contraste com a imagem de destaque.</p>"
            values:
                "#EC7E8B": Rosa
                "#ffffff": Branco
                "#f04e3e": Laranja
                "#000000": Preto
        resumo:
            type: textarea
        corpo:
            type: html
            height: 300px
    taxonomy: [ tags ]
    relations:
        galerias:
            multiple: false
            label: Selecione uma galeria
            postfix: "<p><em>Só escolha uma galeria caso o projeto precise exibir alguma.</em></p>"

itens-biblioteca:
    name: Itens da Biblioteca
    singular_name: Item da Biblioteca
    fields:
        titulo:
            label: Título
            type: text
            class: large
        slug:
            type: slug
            uses: titulo
        resumo:
            type: textarea
        icone:
            label: Ícone
            type: text
            postfix: "<p><em>Escolha o código de um ícone do <a href='http://fontawesome.io/icons/' target='_blank'>Font Awesome</a>. Ex:</em> <code>fa-diamond</code></p>"
    searchable: false

# Tipos de itens da biblioteca
# Cada tipo de conteúdo abaixo é um item da biblioteca
projetos-aprovados:
    name: Bib - Projetos Aprovados
    singular_name: Projeto Aprovado
    fields:
        titulo:
            type: text
            class: large
        slug:
            type: slug
            uses: titulo
        resumo:
            type: textarea
        corpo:
            type: html
            height: 300px
        arquivo:
            type: file

outros-conteudos:
    name: Bib - Outros Conteúdos
    singular_name: Outro Conteúdo
    fields:
        titulo:
            type: text
            class: large
        slug:
            type: slug
            uses: titulo
        resumo:
            type: textarea
        corpo:
            type: html
            height: 300px
        arquivo:
            type: file

linkerias:
    name: Bib - Linkerias
    singular_name: Linkeria
    fields:
        titulo:
            type: text
            class: large
        slug:
            type: slug
            uses: titulo
        corpo:
            type: html
            height: 300px
            postfix: "<p><em>Todos os links são inseridos no corpo.</em></p>"
    default_status: publish

fotos:
    name: Bib - Fotos
    singular_name: Fotos
    fields:
        titulo:
            type: text
            class: large
        slug:
            type: slug
            uses: titulo
        resumo:
            type: textarea
        corpo:
            type: html
            height: 300px
    relations:
        galerias:
            multiple: false
            label: Escolha uma galeria

videos:
    name: Bib - Vídeos
    singular_name: Vídeo
    fields:
        titulo:
            type: text
            class: large
        slug:
            type: slug
            uses: titulo
        resumo:
            type: textarea
        corpo:
            type: html
            height: 300px
        video:
            type: video
# --/

galerias:
    name: Galerias
    singular_name: Galeria
    fields:
        titulo:
            label: Título
            type: text
            class: large
        slug:
            type: slug
            uses: titulo
        imagens:
            type: imagelist
            postfix: "<p><em>É recomendável que todas as imagens tenham o mesmo tamanho, para ficarem alinhadas na exibiçao da página.</em></p>"
        colunas:
            type: select
            values: [ 2, 3, 4, 6 ]
            postfix: "<p><em>Número de colunas que a galeria terá.</em></p>"
    searchable: false
    default_status: publish

slides:
    name: Slides
    singular_name: Slide
    fields:
        titulo:
            label: Título do Slide
            type: text
            class: large
        slug:
            type: slug
            uses: titulo
        imagem:
            type: image
            postfix: "<p><em></em></p>"
        redirecionamento:
            label: Link de redirecionamento, ao clicar no slide
            type: text
            pattern: url
        destino:
            label: Destino do redirecionamento do link
            type: select
            values: { '_blank': "Nova Janela (aba)", '_self': "Mesma Janela" }
            multiple: false
            postfix: "<p><em>Escolha se ao clicar no link será direcionado para uma nova aba ou não</em></p>"
    searchable: false
    default_status: publish

membros:
    name: Membros
    singular_name: Membro
    fields:
        titulo:
            label: Nome do membro da equipe
            type: text
            class: large
        slug:
            type: slug
            uses: titulo
        imagem:
            type: image
        hashtags:
            type: text
    show_on_dashboard: false
    searchable: false
    viewless: true

config-assedio:
    name: Config Assédio
    singular_name: Configuração
    fields:
        titulo:
            label: Título
            type: text
            class: large
            group: Geral
        slug:
            type: slug
            uses: titulo
            group: Geral
        descricao:
            label: Descrição
            type: textarea
            group: Geral
        facebook:
            type: text
            group: Redes Sociais
        Youtube:
            type: text
            group: Redes Sociais
        Instagram:
            type: text
            group: Redes Sociais
        Twitter:
            type: text
            group: Redes Sociais
        logo-site:
            label: Logo do Site
            type: image
            group: Logos
            postfix: "<p><em>Este é o logo principal do site, e não é recomendado alterar.</em></p>"
        logo-site-horizontal:
            label: Logo do Site na versão Horizontal (para mobile)
            type: image
            group: Logos
            postfix: "<p><em>Este é o logo na versão horizontal, que é exibido em dispositivos com resoluções menores.</em></p>"
        logo-menu:
            label: Régua de logos do Menu
            type: image
            group: Logos
            postfix: "<p><em>Esta é a régua de logos que aparece abaixo do menu principal.</em></p>"
        logo-rodape:
            label: Régua de logos do Rodapé
            type: image
            group: Logos
            postfix: "<p><em>Esta é a régua de logo que aparece no rodapé da Home.</em></p>"
        desc-rodape:
            label: Descrição da Assédio no rodapé
            type: textarea
            group: Rodapé
            postfix: "<p><em>Este é o texto que aparece na lateral esquerda do roapé da home, ladeado com o pequeno logo da Assédio.</em></p>"
        logo-assedio-rodape:
            label: Logo da Assédio no rodapé
            type: image
            group: Rodapé
            postfix: "<p><em>Este é o pequeno logo (coração) da Assédio que fica no rodapé.</em></p>"
        hashtags:
            type: html
            group: Rodapé
            postfix: "<p><em>Estas são as hashtags que aparecem no rodapé da home.</em></p>"
        mapa:
            label: Localização
            type: geolocation
            postfix: "<p><em>Localização da Assédio</em></p>"
            group: Página de Contato
        email:
            label: E-mail de contato
            type: text
            postfix: "<p><em>Endereço que receberá os e-mails enviados pelo formulário de conato.</em></p>"
            group: Página de Contato
        telefone:
            label: Telefone de Contato
            type: text
            group: Página de Contato
        corpo:
            label: Corpo da Página de Contato (endereço em três linhas)
            type: textarea
            group: Página de Contato
    show_on_dashboard: false