paginas:
    name: Páginas
    singular_name: Página
    fields:
        titulo:
            label: Título
            type: text
            class: large
        slug:
            type: slug
            uses: titulo
        imagem-destaque:
            label: Imabem de Destaque
            type: image
            postfix: "<p><em>Nem todas as páginas contém uma imagem de destaque exibida, mas é importante adicioná-la, para gerar metatags que serão lidas pelo Facebook.</em></p>"
        resumo:
            type: textarea
        corpo:
            type: html
            height: 300px
    searchable: false

noticias:
    name: Notícias
    singular_name: Notícia
    fields:
        titulo:
            label: Título
            type: text
            class: large
        slug:
            type: slug
            uses: titulo
        titulo-destaque:
            label: Título de Destaque
            type: text
            class: large
            postfix: "<p><em>O título destaque aparece apenas em algumas páginas, como nos blocos da home.</em></p>"
        imagem-destaque:
            label: Imagem de Destaque
            type: image
        resumo:
            type: textarea
        corpo:
            type: html
            height: 300px
        data:
            label: Data do evento (para agenda)
            type: date
            postfix: "<p><em>Só preencha esta informação caso a categoria seja <strong>AGENDA</strong></em></p>"
    taxonomy: [ categorias, tags ]
    relations:
        galerias:
            multiple: false
            label: Selecione uma galeria
            postfix: "<p><em>Só escolha uma galeria caso a notícia precise exibir alguma.</em></p>"

projetos:
    name: Projetos
    singular_name: Projeto
    fields:
        titulo:
            label: Título
            type: text
            class: large
        slug:
            type: slug
            uses: titulo
        titulo-destaque:
            label: Título de Destaque
            type: text
            class: large
            postfix: "<p><em>O título destaque aparece apenas em algumas páginas, como nos blocos da home.</em></p>"
        imagem-destaque:
            label: Imagem de Destaque
            type: image
        logo:
            type: image
            postfix: "<p><em>Este é o logo que aparece no filete do projeto, na galeria de projetos.</p>"
        cor-titulo:
            type: colourpicker
            label: Cor do Título
            postfix: "<p><em>Escolha uma cor que gere contraste com a imagem de destaque.</p>"
            values:
                "#000000": Preto
                "#E1E1E1": Branco
                "#444444": Cinza Escuro
                "#FF0011": Vermelho Claro
        resumo:
            type: textarea
        corpo:
            type: html
            height: 300px
    taxonomy: [ tags ]
    relations:
        galerias:
            multiple: false
            label: Selecione uma galeria
            postfix: "<p><em>Só escolha uma galeria caso o projeto precise exibir alguma.</em></p>"

itens-biblioteca:
    name: Itens da Biblioteca
    singular_name: Item da Biblioteca
    fields:
        titulo:
            label: Título
            type: text
            class: large
        slug:
            type: slug
            uses: titulo
        resumo:
            type: textarea
        icone:
            label: Ícone
            type: text
            postfix: "<p><em>Escolha o código de um ícone do <a href='http://fontawesome.io/icons/' target='_blank'>Font Awesome</a>. Ex:</em> <code>fa fa-diamond</code></p>"
    searchable: false

# Tipos de itens da biblioteca
# Cada tipo de conteúdo abaixo é um item da biblioteca
projetos-aprovados:
    name: Bib - Projetos Aprovados
    singular_name: Projeto Aprovado
    fields:
        titulo:
            type: text
            class: large
        slug:
            type: slug
            uses: titulo
        resumo:
            type: textarea
        corpo:
            type: html
            height: 300px
        arquivo:
            type: file

outros-conteudos:
    name: Bib - Outros Conteúdos
    singular_name: Outro Conteúdo
    fields:
        titulo:
            type: text
            class: large
        slug:
            type: slug
            uses: titulo
        resumo:
            type: textarea
        corpo:
            type: html
            height: 300px
        arquivo:
            type: file

linkerias:
    name: Bib - Linkerias
    singular_name: Linkeria
    fields:
        titulo:
            type: text
            class: large
        slug:
            type: slug
            uses: titulo
        corpo:
            type: html
            height: 300px
            postfix: "<p><em>Todos os links são inseridos no corpo.</em></p>"

fotos:
    name: Bib - Fotos
    singular_name: Fotos
    fields:
        titulo:
            type: text
            class: large
        slug:
            type: slug
            uses: titulo
        resumo:
            type: textarea
        corpo:
            type: html
            height: 300px
    relations:
        galerias:
            multiple: false
            label: Escolha uma galeria

videos:
    name: Bib - Vídeos
    singular_name: Vídeo
    fields:
        titulo:
            type: text
            class: large
        slug:
            type: slug
            uses: titulo
        resumo:
            type: textarea
        corpo:
            type: html
            height: 300px
        video:
            type: video
# --/

galerias:
    name: Galerias
    singular_name: Galeria
    fields:
        titulo:
            type: text
            class: large
        slug:
            type: slug
            uses: titulo
        Imagens:
            type: imagelist
            postfix: "<p><em>É recomendável que todas as imagens tenham o mesmo tamanho, para ficarem alinhadas na exibiçao da página.</em></p>"
        Colunas:
            type: select
            values: [ 2, 3, 4, 6 ]
            postfix: "<p><em>Número de colunas que a galeria terá.</em></p>"
    searchable: false

config-assedio:
    name: Config Assédio
    singular_name: Configuração
    fields:
        titulo:
            type: text
            class: large
            group: Geral
        slug:
            type: slug
            uses: titulo
            group: Geral
        descricao:
            type: textarea
            group: Geral
        facebook:
            type: text
            group: Redes Sociais
        Yutube:
            type: text
            group: Redes Sociais
        Instagram:
            type: text
            group: Redes Sociais
        Twitter:
            type: text
            group: Redes Sociais
        logo-site:
            type: image
            group: Logos
            postfix: "<p><em>Este é o logo principal do site, e não é recomendado alterar.</em></p>"
        logo-menu:
            type: image
            group: Logos
            postfix: "<p><em>Esta é a régua de logos que aparece abaixo do menu principal.</em></p>"
        logo-rodape:
            type: image
            group: Logos
            postfix: "<p><em>Esta é a régua de logo que aparece no rodapé da Home.</em></p>"
        desc-rodape:
            type: textarea
            group: Rodapé
            postfix: "<p><em>Este é o texto que aparece na lateral esquerda do roapé da home, ladeado com o pequeno logo da Assédio.</em></p>"
        logo-assedio-rodape:
            type: image
            group: Rodapé
            postfix: "<p><em>Este é o pequeno logo (coração) da Assédio que fica no rodapé.</em></p>"
        hashtags:
            type: html
            group: Rodapé
            postfix: "<p><em>Estas são as hashtags que aparecem no rodapé da home.</em></p>"
    show_on_dashboard: false
    searchable: false
    viewless: true