main:
  - label: Nós
    path: pagina/nos
    class: first
  - label: Notícias
    path: noticias/
  - label: Projetos
    path: projetos/
  - label: Biblioteca
    path: itens-biblioteca/
  - label: Contato
    path: pagina/contato
  - label: Colabore
    path: pagina/colabore
    class: last
