tags:
    slug: tags
    singular_slug: tag
    behaves_like: tags
    postfix: "Adicione algumas tags de forma livre. Para adicionar uma nova tag, digite depois aperte espaço ou digite uma vírgula."
    #listing_template: tag-listing.twig #custom template

categorias:
    name: Categorias
    slug: categorias
    singular_name: Categoria
    singular_slug: categoria
    behaves_like: categories
    multiple: false
    options: [ 'notícias especiais', 'notícias', 'colaboradores', 'cobertura', 'agenda' ]
